### ISSUE TITLE
Applying filtering and processing to different MS levels

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#114]
Filtering (at least some) and processing function will need to be applied to different levels separately, with different parameters. 
- [ ] `filterMz`, which exists as `trimMz` (to be deprecated in favour of the former) - _lazy_
- [ ] `removePeaks`, `clean` - _lazy_
- [ ] `bin` - _lazy_
- [ ] `pickPeaks` - _lazy_
- [ ] `smooth` - _lazy_

For methods, the MS level is implicit
- [ ] `quantify`: current methods only for MS2. Here, we can figure out based on the specific `method` - produces an `MSnSet` object.
- [ ] `removePrecMz`, only relevant for MS2 - _lazy_
- [ ] `removeReporters` only relevant for MS2 - _lazy_

These methods probably won't need it
- [x] `filterRt` - _immediate_
- [X] `filterMsLevel` - _immediate_
- [x] `filterFile` - _immediate_ (see #122)
- [X] `filterAcquisitionNum` - immediate
- [x] `normalise`/`normalize` - _lazy_

(See [here](https://github.com/lgatto/MSnbase/issues/106#issuecomment-229920000) for a definition of _lazy_ and _immediate_)

- [ ] In addition, some parameters to `readMSData` need to support different MS levels. This is already the case for `centroided` for `OnDiskMSnSet`, but this still needs to be done for smoothed.

**Comment by jotsetung** [comment]
That's great! So, these will be functions, not methods, right?
Note that `filterRt` will also be immediate, as it can be done on the `featureData`. I would also suggest to add a `filterScan` to filter on scan indices (acquisition num).

**Comment by lgatto** [comment]
Most (in not all) of these are already methods (`bin`, `smooth`, `trimMz`, ...). I suggest to make all the `filter*` methods too, so that we can have implementations for `MSnExp` and `OnDiskMSnExp`. 

I suggest to have a `filterMz` in addition to `trimMz` (one calling the other), to keep a nice consistency in the filtering functions naming. 

Wouldn't it be better to call `filterScan` something that makes it obvious that it filters based on the acquisition number, something like `filterAcquisitionNum`

**Comment by lgatto** [comment]
I have prepared the filter* generics and `methods-filters.R` for the `MSnExp` and `OnDiskMSnExp` implementations and `test_MSnExpFilters.R` for the unit tests (which should be based on an `all.equal` method - see #112)

**Comment by jotsetung** [comment]
Great!

**Comment by lgatto** [comment]
**TODO** update `processingData@processing` for *immediate* filters.

**Comment by jotsetung** [comment]
I've added the `filterFile` in commit https://github.com/lgatto/MSnbase/commit/2f9440340a00232fe0ad439c5c4608a047ff39f3 . Two things are however not resolved yet:
* Un-ordered sub-setting, i.e. when file = c(3, 1, 4, 2) . `filterFile` would return the data in the order 1, 2, 3, 4.
* Sub-setting of the `experimentData` (see also issue #122).

**Comment by lgatto** [comment]
> Un-ordered sub-setting, i.e. when `file = c(3, 1, 4, 2)`. `filterFile` would return the data in the order 1, 2, 3, 4.

Is this a problem? There's no specification about the file order anywhere, as far as I can remember.

**Comment by jotsetung** [comment]
No, I don't think that's a problem.

**Comment by jotsetung** [comment]
Done with `filterFile` (commit https://github.com/lgatto/MSnbase/commit/46447afab397b7797e4ea70e30d54268992ddd45).

**Comment by jotsetung** [comment]
Done with `filterAcquisitionNum` (commit https://github.com/lgatto/MSnbase/commit/5afb912ae68ec809a6b6b18f4152bd46518eb2bf).

**Comment by jotsetung** [comment]
Done with `normalize`(commit https://github.com/lgatto/MSnbase/commit/1c4e53766330c13394ca16b54c4f11f969f1f038).
Next to the `msLevel` aware filters... I have to think a little bit how I'm going to do that for the *lazy* filters.

**Comment by jotsetung** [comment]
@lgatto is there a reason behind the `.` in the argument name `msLevel.` in `filterRt`, `filterMsLevel` etc?

**Comment by jotsetung** [comment]
Done with `filterMz`(commit https://github.com/lgatto/MSnbase/commit/cd503512d697a2b42f8468f8c773084cbfdbc2f7).

**Comment by jotsetung** [comment]
`clean` with `msLevel.` argument done in https://github.com/lgatto/MSnbase/commit/5ecf916e4a477e0afdd64a1fb8d14695ead1025c

**Comment by jotsetung** [comment]
`removePeaks` with `msLevel.` argument done in https://github.com/lgatto/MSnbase/commit/18e7fe8c03731f811cc698067e8af8ce5ac23e0a

**Comment by lgatto** [comment]
Because there's a method called `msLevel`. It did have some strange behaviour, but it was possibly not related to that, and I forget to test it again. The user can safely type `msLevel = 2` as R will match partial names.

**Comment by jotsetung** [comment]
`bin` for `OnDiskMSnExp` with additional `msLevel.` argument: commit https://github.com/lgatto/MSnbase/commit/b961a6b82802ee4e6bfcaf0b9c08e9488fc2f826

@lgatto Up to now I've also added the `msLevel.` argument to the `Spectrum` methods (e.g. the `bin` method). That way it is possible to include the MS level specific application of methods with the least code change/performance loss. Somehow I don't have a good feeling about that, since this argument doesn't really fit with the `Spectrum` class. An *ad hoc* solution would be to keep the `msLevel.` argument in the actual function (e.g. `bin_Spectrum`), and pass the `msLevel.` argument *via* the `...` of the `Spectrum` method. What do you think?

**Comment by lgatto** [comment]
If I understand, the `msLevel.` step in required because, when the call to `bin` is executed from the `spectraProcessingQuene`, it is applied to all spectra by default, rather then only to those that actually match `msLevel.`. 

Would it not be possible, at the moment of the call, decide if it needs to be called by checking the MS level and either returned the spectrum as it is, or process it according the the call? This would also avoid unnecessary calls and dispatches.

**Comment by jotsetung** [comment]
the `bin` call with `msLevel. = 2` should only apply the binning to MS level 2, but return all MS 1 spectra as they are. With the current implementation, each method in a processing step in the queue is applied to each spectrum, passing all additional defined arguments to the method as well. At present, the `msLevel.` is also one of the arguments and the e.g. `bin` method for `Spectrum` classes gets this argument and checks on its value whether it should apply the method or just return it (when the MS level of the spectrum does not match `msLevel.`).
This is actually quite efficient, since the spectra have to be loaded anyway from disk, have to be created and returned.

Splitting the spectra before by MS level in the `bin` method of `OnDiskMSnExp` and deciding on which the `bin` method should be applied would not be that efficient (twice `lapply`). Also, with its present implementation parallel processing by file is straight forward, also reducing the amount of memory required.

**Comment by lgatto** [comment]
Ok, fine then.

**Comment by lgatto** [comment]
Quick question: as opposed to the other cases (`bin`, `removePeaks`, ...)  in the `trimMz` method, `msLevel.` is not passed explicitly

```r
setMethod("trimMz",
          signature = signature("Spectrum", "numeric"),
          function(object, mzlim, ...)
              trimMz_Spectrum(object, mzlim, ...))
```
but used in the function
```r
trimMz_Spectrum <- function(x, mzlim, updatePeaksCount=TRUE, msLevel.) {
```

Is this an omission, or is there are reason.

At some point, I will remove most of `trimMz` code other than the deprecated method. Will just keep one un-exported function to be used in a unit test that checks that `trimMz` and `filterMz` produce the same results.

**Comment by jotsetung** [comment]
I missed that one; added in https://github.com/lgatto/MSnbase/commit/afc6dcb042ed40383312c65bc0c6226542ca59bc
