### ISSUE TITLE
Creating Hdf5MSnExp object

### ISSUE THREAD

**Issue by lgatto** [lgatto/MSnbase#393]
Currently, the `readHdf5DiskMSData` function can be used. It first creates and `OnDiskMSnExp` object, then writes the data to disk in an hdf5 files, and finally converts the `OnDiskMSnExp` object into a `Hdf5MSnExp` object that is returned. 

## TODO

- [ ] Add `mode = "hdf5"` to `readMSData`
- [ ] A function to convert an `OnDiskMSnExp` object to `Hdf5MSnExp`. Unfortunately, `as()` won't work as it doesn't support additional arguments, and we need to be able to set the hdf5 file name. 
- [ ] A public function that serialises data to disk, for when the hdf5 file gets deleted. Currently, there's `serialise_to_hdf5`.

If might also be useful to be to access and modify the hdf5 filename 
- [x] `hdf5FileName` returns the hdf5 filename
- [x] `hdf5FileName<-` can be used to modify it in the object and rename the hdf5 file (this would allow to have a `as(OnDiskMSnExp, Hdf5MSnExp)` function that defines a unique filename by default that could then be changed).

**Comment by jotsetung** [comment]
Question: is the conversion done on a per-file basis? i.e. reading only spectra data from one file and saving that to the hdf5 then proceeding to the next? This would be required to process larger experiments as you would run out of memory otherwise.

**Comment by lgatto** [comment]
> Is the conversion done on a per-file basis?

Yes, it is. The relevant code is [here](https://github.com/lgatto/MSnbase/blob/hdf5/R/hdf5.R#L84-L86): each `mzR` file handle is created in turn, all peaks are read in memory, then written iteratively to hdf5.

**Comment by jotsetung** [comment]
Let me know when you need some beta testers - I'm running some analyses and am unhappy with the performance of the `OnDiskMSnExp`...

**Comment by lgatto** [comment]
You could already give it a go now. I was waiting before implementing `spectra` to hear about parallel read/write access (see #391), but I could make progress irrespective. Or let me know if you have specific needs. There's also some initial [documentation](https://github.com/lgatto/MSnbase/blob/hdf5/man/Hdf5MSnExp-class.Rd).

**Comment by jotsetung** [comment]
makes sense to wait until parallel read access is here - otherwise I'm not sure if we can have a speed improvement.

**Comment by jotsetung** [comment]
All the new code is in the *hdf5.R* file I suppose? I'll have a look.

**Comment by lgatto** [comment]
Yes, I would like to keep it there for now, and then dispatch it in the appropriate files before merging.

**Comment by lgatto** [comment]
@jotsetung - see #391

**Comment by jotsetung** [comment]
I would also go for a single file - as long as we don't run into parallel processing issues.
